name: AddHugoPost

on:
  push:
    branches:
      - main
    paths:
      - published/**

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: stage changed files
        run: git add .

      - name: commit changed files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto updating"

      - name: push out to posts branch
        run: |
          git subtree split --branch posts --prefix published/
          git push -f origin posts
