name: UpdatePosts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to posts branch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Push to repo
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: git@github.com:h3x0c4t/h3x0c4t.github.io.git
          BRANCH: posts
          FOLDER: published
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}